export const ideas = {
    Restaurant: [
      "Dinner at a cozy rooftop bistro",
      "Wine tasting at a vineyard",
      "Fondue night for two",
      "Vegan tasting menu",
      "Sushi omakase experience",
      "Picnic in the park with charcuterie",
      "Tapas and sangria date",
      "Dessert-only café crawl",
      "Brunch with live jazz",
      "Food truck festival sampling tour",
    ],
    Activity: [
      "Paint & Sip class",
      "Pottery workshop",
      "Escape room challenge",
      "Axe throwing session",
      "Comedy club night",
      "Outdoor movie screening",
      "Stargazing night with telescope",
      "Karaoke battle night",
      "Cooking class for two",
      "Art gallery hop with wine breaks",
    ],
    Sports: [
      "Rock climbing challenge",
      "Mini golf competition",
      "Bike ride through nature trails",
      "Ice skating in the evening",
      "Bowling night with funny shoes",
      "Try pickleball together",
      "Go-kart racing like kids",
      "Rollerblading by the waterfront",
      "Attend a local sports game",
      "Beach volleyball if it's warm",
    ],
    Travel: [
      "Weekend road trip to a small town",
      "Staycation in a themed Airbnb",
      "Sunset ferry ride",
      "Explore a nearby island",
      "Mountain hike with a picnic",
      "Book a spa weekend getaway",
      "Take a train to a new city",
      "Visit a waterfall you've never seen",
      "Book a surprise mystery destination",
      "Try a new hotel just for fun",
    ],
  };
  